version: '3.8'

services:
  mongo:
    build:
      context: . 
      dockerfile: ./dockerfiles/mongo/Dockerfile
    image: mongo_velas_miguel
    container_name: mongo
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo