version: '3.8'

services:
  mongo:
    build:
      context: . 
      dockerfile: ./dockerfiles/mongo/Dockerfile
    image: mongo_velas_miguel
    container_name: mongo
    ports:
      - 27017:27017

