version: '3.8'

services:
  mongo:
    build:
      context: . 
      dockerfile: ./dockerfiles/mongo/Dockerfile
    image: mongo_velas_miguel
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - agile_net


  kafka:
    build:
      context: .
      dockerfile: ./dockerfiles/kafka/Dockerfile
    image: kafka_velas_miguel
    container_name: kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_ADVERTISED_LISTENERS:PLAINTEXT://kafka:9092
    ports:
      - '9092:9092'
    networks:
      - agile_net

networks:
  agile_net:
    driver: bridge

