version: '3.8'

services:
  cassandra:
    build:
      context: .
      dockerfile: ./dockerfiles/cassandra/Dockerfile
    container_name: cassandra
    hostname: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra

